import { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Ethereal Bloom",
    price: 89.0,
    image: "/images/hero-main.png",
    description: "A delicate arrangement of white roses and eucalyptus, perfect for minimalist aesthetics.",
    categoryId: 1,
    style: "Minimalist",
    occasion: "Wedding",
  },
  {
    id: 2,
    name: "Garden Romance",
    price: 125.0,
    image: "/images/birthday.png",
    description: "Lush peonies and garden roses in soft blush tones, evoking timeless romance.",
    categoryId: 2,
    style: "Classic Luxe",
    occasion: "Anniversary",
  },
  {
    id: 3,
    name: "Wildflower Meadow",
    price: 68.0,
    image: "/images/anniversary.png",
    description: "A rustic mix of seasonal wildflowers, celebrating nature's untamed beauty.",
    categoryId: 3,
    style: "Rustic",
    occasion: "Birthday",
  },
  {
    id: 4,
    name: "Sunset Serenade",
    price: 95.0,
    image: "/images/sympathy.png",
    description: "Warm amber and coral blooms that capture the glow of golden hour.",
    categoryId: 1,
    style: "Modern",
    occasion: "Celebration",
  },
  {
    id: 5,
    name: "Velvet Noir",
    price: 145.0,
    image: "/images/process-step-2.png",
    description: "Deep burgundy roses and black calla lilies for a dramatic, moody statement.",
    categoryId: 2,
    style: "Dramatic",
    occasion: "Event",
  },
  {
    id: 6,
    name: "Spring Whisper",
    price: 72.0,
    image: "/images/process-step-3.png",
    description: "Soft pastels of tulips and ranunculus, a gentle nod to spring's arrival.",
    categoryId: 3,
    style: "Soft & Romantic",
    occasion: "Birthday",
  },
  {
    id: 7,
    name: "Ivory Elegance",
    price: 110.0,
    image: "/images/heritage-main.png",
    description: "Monochromatic white blooms with textured greenery for refined sophistication.",
    categoryId: 1,
    style: "Classic Luxe",
    occasion: "Wedding",
  },
  {
    id: 8,
    name: "Citrus Grove",
    price: 85.0,
    image: "/images/gallery-photo.png",
    description: "Bright yellow and orange blooms that bring sunshine indoors.",
    categoryId: 3,
    style: "Vibrant",
    occasion: "Celebration",
  },
  {
    id: 9,
    name: "Lavender Dreams",
    price: 78.0,
    image: "/images/hero-main.png",
    description: "Calming lavender and lilac tones for a serene, spa-like ambiance.",
    categoryId: 2,
    style: "Soft & Romantic",
    occasion: "Sympathy",
  },
  {
    id: 10,
    name: "Tropical Escape",
    price: 135.0,
    image: "/images/birthday.png",
    description: "Exotic orchids and birds of paradise for a bold, adventurous look.",
    categoryId: 1,
    style: "Tropical",
    occasion: "Event",
  },
  {
    id: 11,
    name: "Autumn Harvest",
    price: 92.0,
    image: "/images/anniversary.png",
    description: "Rich burgundy, rust, and gold blooms celebrating the fall season.",
    categoryId: 3,
    style: "Rustic",
    occasion: "Thanksgiving",
  },
  {
    id: 12,
    name: "Moonlight Garden",
    price: 105.0,
    image: "/images/sympathy.png",
    description: "Silvery whites and soft blues, inspired by a garden under moonlight.",
    categoryId: 2,
    style: "Minimalist",
    occasion: "Anniversary",
  },
];
